name: "web_app44"
mode: "dev"
starttime: "2021-10-27"
machine_id: 22
port: 8081
jwt_secret: "rolinabc12311"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 300
  max_age: 31
  max_backups: 30

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "rolinabc123"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  poolsize: ""

version:
  version: "0.0.5"


